# Source: cluster-api-aws/templates/job-check.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: 1a33645c-b816-4328-a60a-8f785ffda0c5-capi-aws-check
  namespace: 1a33645c-b816-4328-a60a-8f785ffda0c5
spec:
  template:
    metadata:
      name: 1a33645c-b816-4328-a60a-8f785ffda0c5-capi-aws
    spec:
      serviceAccountName: 1a33645c-b816-4328-a60a-8f785ffda0c5-capi-aws
      containers:
      - name: wait-for-ready
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout 
        - 5m
        - /wait_for_kubeconfig.sh  
        - 1a33645c-b816-4328-a60a-8f785ffda0c5
        - 1a33645c-b816-4328-a60a-8f785ffda0c5
        volumeMounts:
        - name: vol
          subPath: wait_for_kubeconfig.sh
          mountPath: /wait_for_kubeconfig.sh
      volumes:
      - name: vol
        configMap:
          name: 1a33645c-b816-4328-a60a-8f785ffda0c5-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure
