# Source: cluster-autoscaler/templates/rbac-for-mgmt-cluster-access.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-autoscaler-management
  namespace: 1a33645c-b816-4328-a60a-8f785ffda0c5
rules:
  - apiGroups:
    - cluster.x-k8s.io
    resources:
    - machinedeployments
    - machinedeployments/scale
    - machines
    - machinesets
    verbs:
    - get
    - list
    - update
    - watch
